#!/usr/bin/env ruby
# frozen_string_literal: true

# Versioned build of the docs site. Run by .github/workflows/docs.yml on every
# push to main that touches docs/, and runnable locally the same way.
#
#   scripts/docs-build.rb --archive DIR --out DIR [--bump patch|minor|major]
#                         [--commit SHA] [--summary TEXT] [--released YYYY-MM-DD]
#
# --archive is a checkout of the `docs-versions` branch (an empty dir is fine
# for the very first build). It holds manifest.yml plus one frozen static
# build per released version, at <version>/.
#
# Each run:
#   1. Picks the next version: 1.0.0 for an empty archive, otherwise the
#      newest archived version bumped by --bump (default patch).
#   2. Writes docs/_data/versions.yml, which the header badge and the
#      Versions page read.
#   3. Builds this version as a frozen snapshot (baseurl /versions/<v>/,
#      labelled archived) into <archive>/<v>/ and records it in the manifest.
#   4. Builds the live site into --out, then copies every archived snapshot
#      into <out>/versions/<v>/.
#
# Committing the archive dir back to docs-versions and deploying --out are
# the caller's job (the workflow does both).

require "date"
require "fileutils"
require "optparse"
require "tmpdir"
require "yaml"

ROOT = File.expand_path("..", __dir__)
DOCS = File.join(ROOT, "docs")
DATA_FILE = File.join(DOCS, "_data", "versions.yml")
BUMPS = %w[patch minor major].freeze

def abort_with(msg)
  warn "docs-build: #{msg}"
  exit 1
end

opts = { bump: "patch", released: Date.today.iso8601 }
OptionParser.new do |o|
  o.on("--archive DIR") { |v| opts[:archive] = File.expand_path(v) }
  o.on("--out DIR") { |v| opts[:out] = File.expand_path(v) }
  o.on("--bump LEVEL", BUMPS) { |v| opts[:bump] = v }
  o.on("--commit SHA") { |v| opts[:commit] = v }
  o.on("--summary TEXT") { |v| opts[:summary] = v }
  o.on("--released DATE") { |v| opts[:released] = v }
end.parse!
abort_with "--archive and --out are required" unless opts[:archive] && opts[:out]

def next_version(latest, bump)
  return "1.0.0" unless latest

  major, minor, patch = latest.split(".").map(&:to_i)
  case bump
  when "major" then "#{major + 1}.0.0"
  when "minor" then "#{major}.#{minor + 1}.0"
  else "#{major}.#{minor}.#{patch + 1}"
  end
end

def jekyll_build(dest, overlay = nil)
  configs = ["_config.yml", overlay].compact.join(",")
  Dir.chdir(DOCS) do
    ok = system("bundle", "exec", "jekyll", "build", "--config", configs, "--destination", dest)
    abort_with "jekyll build failed (#{dest})" unless ok
  end
end

FileUtils.mkdir_p(opts[:archive])
manifest_path = File.join(opts[:archive], "manifest.yml")
manifest = File.exist?(manifest_path) ? (YAML.safe_load(File.read(manifest_path)) || {}) : {}
versions = manifest["versions"] || []
versions.sort_by! { |v| Gem::Version.new(v["version"]) }.reverse!

version = next_version(versions.first&.fetch("version"), opts[:bump])
abort_with "#{opts[:archive]}/#{version} already exists" if File.exist?(File.join(opts[:archive], version))

current = { "version" => version, "released" => opts[:released] }
current["commit"] = opts[:commit] if opts[:commit]
current["summary"] = opts[:summary].lines.first.strip if opts[:summary] && !opts[:summary].strip.empty?

FileUtils.mkdir_p(File.dirname(DATA_FILE))
File.write(DATA_FILE, <<~HEAD + { "current" => current, "archive" => versions }.to_yaml.sub(/\A---\n/, ""))
  # GENERATED by scripts/docs-build.rb on every GitHub build. Not committed;
  # edits here are overwritten. The real history lives on the docs-versions
  # branch (manifest.yml).
HEAD
puts "docs-build: building v#{version} (#{opts[:bump]} bump from #{versions.first&.fetch('version') || 'nothing'})"

config = YAML.safe_load(File.read(File.join(DOCS, "_config.yml")))

Dir.mktmpdir("docs-build-") do |tmp|
  # 1. Frozen snapshot of this version.
  overlay = File.join(tmp, "_config.archive.yml")
  snapshot = File.join(tmp, "snapshot")
  File.write(overlay, {
    "baseurl" => "#{config.fetch('baseurl')}/versions/#{version}",
    "version_archive_build" => true,
    # A snapshot never contains the archive itself.
    "exclude" => (config["exclude"] || []) + ["versions"],
  }.to_yaml)
  jekyll_build(snapshot, overlay)
  # Site-root-only files mean nothing inside a subdirectory.
  %w[robots.txt sitemap.xml 404.html].each { |f| FileUtils.rm_f(File.join(snapshot, f)) }
  FileUtils.cp_r(snapshot, File.join(opts[:archive], version))
end

versions.unshift(current)
File.write(manifest_path, <<~HEAD + { "versions" => versions }.to_yaml.sub(/\A---\n/, ""))
  # Every released version of the docs site, newest first. Written by
  # scripts/docs-build.rb on main's GitHub build; each entry has a frozen
  # static copy at <version>/ on this branch, served at /versions/<version>/.
HEAD

# 2. Live site, with every archived snapshot alongside it.
FileUtils.rm_rf(opts[:out])
jekyll_build(opts[:out])
versions.each do |v|
  src = File.join(opts[:archive], v["version"])
  abort_with "manifest lists v#{v['version']} but #{src} is missing" unless File.directory?(src)
  FileUtils.mkdir_p(File.join(opts[:out], "versions"))
  FileUtils.cp_r(src, File.join(opts[:out], "versions", v["version"]))
end

File.write(ENV["GITHUB_OUTPUT"], "version=#{version}\n", mode: "a") if ENV["GITHUB_OUTPUT"]
puts "docs-build: v#{version} built into #{opts[:out]} with #{versions.size} archived version(s)"
